apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-lando-web
  namespace: dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/tmp"
    type: Directory
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lando-web
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi