apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-lando-web
spec:
  replicas: 2
  selector:
    app: website
  template:
    metadata:
      name: lando-web
      labels:
        app: website
        version: 1.0.1
    spec:
      containers:
        - name: lando-web
          image: lando45/lando-web:latest
          ports:
            - containerPort: 80
          