apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-lando-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
    matchExpressions:
      - key: version
        operator: In
        values:
          - 1.0.1
  template:
    metadata:
      name: lando-web
      labels:
        app: website
        version: 1.0.1
    spec:
      containers:
        - name: lando-web
          image: lando45/lando-web:latest
          ports:
            - containerPort: 80
          