apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-lando-web
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
    matchExpressions:
      - key: version
        operator: In
        values:
          - 1.0.1
  template:
    metadata:
      name: lando-web
      namespace: dev
      labels:
        app: website
        version: 1.0.1
    spec:
      containers:
        - name: lando-web
          image: lando45/lando-web:latest
          volumeMounts:
            - mountPath: /var/www/html
              name: volume-lando-web
          ports:
            - containerPort: 80
      volumes:
        - name: volume-lando-web
          persistentVolumeClaim:
            claimName: pvc-lando-web
            
---          
          
apiVersion: v1
kind: Service
metadata:
  name: service-lando-web
  namespace: dev
spec:
  selector:
    app: website
  ports:
    - port: 80
      targetPort: 80
      
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-lando-web
  namespace: dev
  labels:
    name: ingress-lando-web
spec:
  rules:
    - host: lando-web.lando45.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-lando-web
                port: 
                  number: 80